# Generated by Django 3.2.5 on 2021-09-26 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='date_updated',
            new_name='last_update',
        ),
    ]
